
--------------------------------------------------------
--  File created - Sunday-August-28-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence OGRENCINO
--------------------------------------------------------

   CREATE SEQUENCE  "HR"."OGRENCINO"  MINVALUE 1 MAXVALUE 999999999999999999 INCREMENT BY 1 START WITH 181 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence OGRENCI_NO
--------------------------------------------------------

   CREATE SEQUENCE  "HR"."OGRENCI_NO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence OGRETMENID
--------------------------------------------------------

   CREATE SEQUENCE  "HR"."OGRETMENID"  MINVALUE 1 MAXVALUE 999999999999999999 INCREMENT BY 1 START WITH 4975 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence VELIID
--------------------------------------------------------

   CREATE SEQUENCE  "HR"."VELIID"  MINVALUE 1 MAXVALUE 999999999999999999 INCREMENT BY 1 START WITH 273 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence YONETICIID
--------------------------------------------------------

   CREATE SEQUENCE  "HR"."YONETICIID"  MINVALUE 1 MAXVALUE 999999999999999999 INCREMENT BY 1 START WITH 1935 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table DERS_NOTLARI
--------------------------------------------------------

  CREATE TABLE "HR"."DERS_NOTLARI" 
   (	"NOT_ID" NUMBER, 
	"OGRENCI_ID" NUMBER, 
	"DONEM" VARCHAR2(100 BYTE), 
	"TURKCE" VARCHAR2(100 BYTE), 
	"HAYAT_BILGISI" VARCHAR2(100 BYTE), 
	"SOSYAL_AKTIVITE" VARCHAR2(100 BYTE), 
	"KAYIT_TARIHI" DATE, 
	"SINIF_ID" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table GIRISLER
--------------------------------------------------------

  CREATE TABLE "HR"."GIRISLER" 
   (	"GIRIS_ID" NUMBER, 
	"KULLANICI_ADI" VARCHAR2(100 BYTE), 
	"GIRIS_TARIHI" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ODEMELER
--------------------------------------------------------

  CREATE TABLE "HR"."ODEMELER" 
   (	"VELI_ID" NUMBER, 
	"OGRENCI_ID" NUMBER, 
	"TAKSIT_SAYISI" NUMBER, 
	"KAYIT_TARIHI" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table OGRENCILER
--------------------------------------------------------

  CREATE TABLE "HR"."OGRENCILER" 
   (	"OGRENCI_ID" NUMBER, 
	"ADI" VARCHAR2(255 BYTE), 
	"SOYADI" VARCHAR2(100 BYTE), 
	"TCKN" NUMBER, 
	"KAN_GRUBU" VARCHAR2(20 BYTE), 
	"EV_ADRESI" VARCHAR2(255 BYTE), 
	"DOGUM_TARIHI" DATE, 
	"DOGUM_YERI" VARCHAR2(255 BYTE), 
	"VELI_ID" NUMBER, 
	"SINIF_ID" VARCHAR2(20 BYTE), 
	"KAYIT_TARIHI" TIMESTAMP (6), 
	"TAKSIT_SAYISI" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table OGRENCILER_YEDEK
--------------------------------------------------------

  CREATE TABLE "HR"."OGRENCILER_YEDEK" 
   (	"OGRENCI_ID" NUMBER, 
	"ADI" VARCHAR2(255 BYTE), 
	"SOYADI" VARCHAR2(100 BYTE), 
	"TCKN" NUMBER, 
	"KAN_GRUBU" VARCHAR2(20 BYTE), 
	"EV_ADRESI" VARCHAR2(255 BYTE), 
	"DOGUM_TARIHI" DATE, 
	"DOGUM_YERI" VARCHAR2(255 BYTE), 
	"VELI_ID" NUMBER, 
	"SINIF_ID" VARCHAR2(20 BYTE), 
	"KAYIT_TARIHI" TIMESTAMP (6), 
	"TAKSIT_SAYISI" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table OGRENCI_ESKI
--------------------------------------------------------

  CREATE TABLE "HR"."OGRENCI_ESKI" 
   (	"SINIF_ID" VARCHAR2(20 BYTE), 
	"KAYIT_TARIHI" TIMESTAMP (6), 
	"OGRENCI_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table OGRETMENLER
--------------------------------------------------------

  CREATE TABLE "HR"."OGRETMENLER" 
   (	"OGRETMEN_ID" NUMBER, 
	"ADI" VARCHAR2(140 BYTE), 
	"SOYADI" VARCHAR2(140 BYTE), 
	"TCKN" NUMBER, 
	"TELEFON_NUMARASI" NUMBER, 
	"DOGUM_TARIHI" DATE, 
	"DOGUM_YERI" VARCHAR2(155 BYTE), 
	"KAYIT_TARIHI" TIMESTAMP (6), 
	"KULLANICI_ADI" VARCHAR2(100 BYTE), 
	"KULLANICI_SIFRE" VARCHAR2(100 BYTE), 
	"SINIF_ID" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SINIFLAR
--------------------------------------------------------

  CREATE TABLE "HR"."SINIFLAR" 
   (	"SINIF_ID" VARCHAR2(20 BYTE), 
	"SINIF_ADI" VARCHAR2(140 BYTE), 
	"OGRETMEN_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table VELILER
--------------------------------------------------------

  CREATE TABLE "HR"."VELILER" 
   (	"VELI_ID" NUMBER, 
	"ADI" VARCHAR2(255 BYTE), 
	"SOYADI" VARCHAR2(255 BYTE), 
	"TCKN" NUMBER, 
	"DOGUM_TARIHI" DATE, 
	"DOGUM_YERI" VARCHAR2(20 BYTE), 
	"KULLANICI_ADI" VARCHAR2(155 BYTE), 
	"KULLANICI_SIFRE" VARCHAR2(100 BYTE), 
	"MESLEK" VARCHAR2(140 BYTE), 
	"TELEFON_NUMARASI" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table YONETICILER
--------------------------------------------------------

  CREATE TABLE "HR"."YONETICILER" 
   (	"YONETICI_ID" NUMBER, 
	"ADI" VARCHAR2(20 BYTE), 
	"SOYADI" VARCHAR2(20 BYTE), 
	"TCKN" NUMBER, 
	"TELEFON_NUMARASI" NUMBER, 
	"KULLANICI_ADI" VARCHAR2(100 BYTE), 
	"KULLANICI_SIFRE" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  
--------------------------------------------------------
--  DDL for Index OGRETMENLER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."OGRETMENLER_PK" ON "HR"."OGRETMENLER" ("OGRETMEN_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SINIFLAR_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."SINIFLAR_PK" ON "HR"."SINIFLAR" ("SINIF_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index YONETICILER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."YONETICILER_PK" ON "HR"."YONETICILER" ("YONETICI_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index DERS_NOTLARI_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."DERS_NOTLARI_PK" ON "HR"."DERS_NOTLARI" ("NOT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index GIRISLER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."GIRISLER_PK" ON "HR"."GIRISLER" ("GIRIS_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

--------------------------------------------------------
--  DDL for Index OGRENCILER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."OGRENCILER_PK" ON "HR"."OGRENCILER" ("OGRENCI_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index VELILER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."VELILER_PK" ON "HR"."VELILER" ("VELI_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table YONETICILER
--------------------------------------------------------

  ALTER TABLE "HR"."YONETICILER" ADD CONSTRAINT "YONETICILER_PK" PRIMARY KEY ("YONETICI_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HR"."YONETICILER" MODIFY ("YONETICI_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table OGRENCILER_YEDEK
--------------------------------------------------------

  ALTER TABLE "HR"."OGRENCILER_YEDEK" MODIFY ("SINIF_ID" NOT NULL ENABLE);
  ALTER TABLE "HR"."OGRENCILER_YEDEK" MODIFY ("OGRENCI_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SINIFLAR
--------------------------------------------------------

  ALTER TABLE "HR"."SINIFLAR" ADD CONSTRAINT "SINIFLAR_PK" PRIMARY KEY ("SINIF_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HR"."SINIFLAR" MODIFY ("SINIF_ID" NOT NULL ENABLE);

--------------------------------------------------------
--  Constraints for Table VELILER
--------------------------------------------------------

  ALTER TABLE "HR"."VELILER" ADD CONSTRAINT "VELILER_PK" PRIMARY KEY ("VELI_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HR"."VELILER" MODIFY ("VELI_ID" NOT NULL ENABLE);


--------------------------------------------------------
--  Constraints for Table GIRISLER
--------------------------------------------------------

  ALTER TABLE "HR"."GIRISLER" ADD CONSTRAINT "GIRISLER_PK" PRIMARY KEY ("GIRIS_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HR"."GIRISLER" MODIFY ("GIRIS_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table OGRETMENLER
--------------------------------------------------------

  ALTER TABLE "HR"."OGRETMENLER" ADD CONSTRAINT "OGRETMENLER_PK" PRIMARY KEY ("OGRETMEN_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HR"."OGRETMENLER" MODIFY ("KULLANICI_SIFRE" NOT NULL ENABLE);
  ALTER TABLE "HR"."OGRETMENLER" MODIFY ("KULLANICI_ADI" NOT NULL ENABLE);
  ALTER TABLE "HR"."OGRETMENLER" MODIFY ("KAYIT_TARIHI" NOT NULL ENABLE);
  ALTER TABLE "HR"."OGRETMENLER" MODIFY ("DOGUM_YERI" NOT NULL ENABLE);
  ALTER TABLE "HR"."OGRETMENLER" MODIFY ("DOGUM_TARIHI" NOT NULL ENABLE);
  ALTER TABLE "HR"."OGRETMENLER" MODIFY ("TELEFON_NUMARASI" NOT NULL ENABLE);
  ALTER TABLE "HR"."OGRETMENLER" MODIFY ("TCKN" NOT NULL ENABLE);
  ALTER TABLE "HR"."OGRETMENLER" MODIFY ("SOYADI" NOT NULL ENABLE);
  ALTER TABLE "HR"."OGRETMENLER" MODIFY ("ADI" NOT NULL ENABLE);
  ALTER TABLE "HR"."OGRETMENLER" MODIFY ("OGRETMEN_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table OGRENCILER
--------------------------------------------------------

  ALTER TABLE "HR"."OGRENCILER" MODIFY ("SINIF_ID" NOT NULL ENABLE);
  ALTER TABLE "HR"."OGRENCILER" ADD CONSTRAINT "OGRENCILER_PK" PRIMARY KEY ("OGRENCI_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HR"."OGRENCILER" MODIFY ("OGRENCI_ID" NOT NULL ENABLE);

--------------------------------------------------------
--  Constraints for Table DERS_NOTLARI
--------------------------------------------------------

  ALTER TABLE "HR"."DERS_NOTLARI" ADD CONSTRAINT "DERS_NOTLARI_PK" PRIMARY KEY ("NOT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HR"."DERS_NOTLARI" MODIFY ("NOT_ID" NOT NULL ENABLE);
  ALTER TABLE "HR"."DERS_NOTLARI" MODIFY ("KAYIT_TARIHI" NOT NULL ENABLE);
  ALTER TABLE "HR"."DERS_NOTLARI" MODIFY ("OGRENCI_ID" NOT NULL ENABLE);

--------------------------------------------------------
--  DDL for Trigger ODEME_EKLEME
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "HR"."ODEME_EKLEME" 
AFTER INSERT  ON OGRENCILER
   FOR EACH ROW
   BEGIN

   INSERT INTO ODEMELER
   ( VELI_ID,
     OGRENCI_ID, TAKSIT_SAYISI,
     KAYIT_TARIHI)
   VALUES
   (:new.VELI_ID, 
   :new.OGRENCI_ID,
     :new.TAKSIT_SAYISI,
     sysdate);

END;
/
ALTER TRIGGER "HR"."ODEME_EKLEME" ENABLE;
--------------------------------------------------------
--  DDL for Trigger OGRENCIID
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "HR"."OGRENCIID" 
before insert on OGRENCILER
referencing new as new old as old
for each row
declare
    integrity_error exception;
    errno integer;
    errmsg char(200);
    dummy integer;
    found boolean;
begin
    select ogrenciNo.nextval into :new.OGRENCI_ID from dual;
exception
    when integrity_error then
        raise_application_error(errno, errmsg);
end;
/
ALTER TRIGGER "HR"."OGRENCIID" ENABLE;
--------------------------------------------------------
--  DDL for Trigger OGRENCI_SILME_SONRASI
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "HR"."OGRENCI_SILME_SONRASI" 
AFTER DELETE  ON OGRENCILER
   FOR EACH ROW
   BEGIN

   -- Insert record into audit table
   INSERT INTO OGRENCI_ESKI
   ( OGRENCI_ID,
     SINIF_ID,
     KAYIT_TARIHI)
   VALUES
   ( :old.OGRENCI_ID,
     :old.SINIF_ID,
     
     sysdate);

END;
/
ALTER TRIGGER "HR"."OGRENCI_SILME_SONRASI" ENABLE;
--------------------------------------------------------
--  DDL for Trigger OGRETMENID
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "HR"."OGRETMENID" 
before insert on OGRETMENLER
referencing new as new old as old
for each row
declare
    integrity_error exception;
    errno integer;
    errmsg char(200);
    dummy integer;
    found boolean;
begin
    select ogretmenID.nextval into :new.OGRETMEN_ID from dual;
exception
    when integrity_error then
        raise_application_error(errno, errmsg);
end;
/
ALTER TRIGGER "HR"."OGRETMENID" ENABLE;
--------------------------------------------------------
--  DDL for Trigger OGRETMEN_SINIF_ATAMA
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "HR"."OGRETMEN_SINIF_ATAMA" 
AFTER INSERT OR UPDATE ON OGRETMENLER
   FOR EACH ROW
   BEGIN

   UPDATE SINIFLAR
   SET OGRETMEN_ID = :new.OGRETMEN_ID
  WHERE SINIF_ID =:new.SINIF_ID;

END;
/
ALTER TRIGGER "HR"."OGRETMEN_SINIF_ATAMA" ENABLE;

--------------------------------------------------------
--  DDL for Trigger VELIID
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "HR"."VELIID" 
before insert on VELILER
referencing new as new old as old
for each row
declare
    integrity_error exception;
    errno integer;
    errmsg char(200);
    dummy integer;
    found boolean;
begin
    select veliId.nextval into :new.VELI_ID from dual;
exception
    when integrity_error then
        raise_application_error(errno, errmsg);
end;
/
ALTER TRIGGER "HR"."VELIID" ENABLE;
--------------------------------------------------------
--  DDL for Trigger YONETICIID
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "HR"."YONETICIID" 
before insert on YONETICILER
referencing new as new old as old
for each row
declare
    integrity_error exception;
    errno integer;
    errmsg char(200);
    dummy integer;
    found boolean;
begin
    select yoneticiID.nextval into :new.YONETICI_ID from dual;
exception
    when integrity_error then
        raise_application_error(errno, errmsg);
end;
/
ALTER TRIGGER "HR"."YONETICIID" ENABLE;
--------------------------------------------------------
--  DDL for Procedure SECURE_DML
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "HR"."SECURE_DML" 
IS
BEGIN
  IF TO_CHAR (SYSDATE, 'HH24:MI') NOT BETWEEN '08:00' AND '18:00'
        OR TO_CHAR (SYSDATE, 'DY') IN ('SAT', 'SUN') THEN
	RAISE_APPLICATION_ERROR (-20205,
		'You may only make changes during normal office hours');
  END IF;
END secure_dml;

/